@extends('layouts.app')
@section( 'content' )
    <div class="container">

        <h2><a id="Privacy_Policy_5"></a>Privacy Policy</h2>
        <p>Your privacy is critically important to us. At CalderaWP we have a few fundamental principles:</p>
        <ul>
            <li>We don’t ask you for personal information unless we truly need it. (We can’t stand services that ask you for things like your gender or income level for no apparent reason.)</li>
            <li>We don’t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li>
            <li>We don’t store personal information on our servers unless required for the on-going operation of one of our services.</li>
        </ul>
        <p>If you have questions about deleting or correcting your personal data please  <a href="https://calderawp.com/contact">contact us</a>.</p>
        <p>CalderaWP LLC (“<strong>CalderaWP</strong>”) operates several websites including <a href="https://caldera.space/">Caldera Space</a> and <a href="https://calderawp.com/">CalderaWP.com</a>  It is CalderaWP’s policy to respect your privacy regarding any information we may collect while operating our websites.</p>
        <h3><a id="Website_Visitors_19"></a>Website Visitors</h3>
        <p>Like most website operators, CalderaWP collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. CalderaWP’s purpose in collecting non-personally identifying information is to better understand how CalderaWP’s visitors use its website. From time to time, CalderaWP may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
        <p>CalderaWP also collects potentially personally-identifying information like Internet Protocol (IP) addresses. CalderaWP only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that blog commenter IP addresses and email addresses are visible and disclosed to the administrators of the blog where the comment was left.</p>
        <h3><a id="Protection_of_Certain_PersonallyIdentifying_Information_33"></a>Protection of Certain Personally-Identifying Information</h3>
        <p>CalderaWP discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on CalderaWP’s behalf or to provide services available at CalderaWP’s websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using CalderaWP’s websites, you consent to the transfer of such information to them. CalderaWP will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, CalderaWP discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when CalderaWP believes in good faith that disclosure is reasonably necessary to protect the property or rights of CalderaWP, third parties or the public at large. If you are a registered user of an CalderaWP website and have supplied your email address, CalderaWP may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with CalderaWP and our products. We primarily use our various product blogs to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. CalderaWP takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
        <h3><a id="Cookies_37"></a>Cookies</h3>
        <p>A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. CalderaWP uses cookies to help CalderaWP identify and track visitors, their usage of CalderaWP website, and their website access preferences. CalderaWP visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using CalderaWP’s websites, with the drawback that certain features of CalderaWP’s websites may not function properly without the aid of cookies.</p>
        <h3><a id="Business_Transfers_41"></a>Business Transfers</h3>
        <p>If CalderaWP, or substantially all of its assets, were acquired, or in the unlikely event that CalderaWP goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of CalderaWP may continue to use your personal information as set forth in this policy.</p>

        <h3><a id="Privacy_Policy_Changes_53"></a>Privacy Policy Changes</h3>
        <p>Although most changes are likely to be minor, CalderaWP may change its Privacy Policy from time to time, and in CalderaWP’s sole discretion. CalderaWP encourages visitors to frequently check this page for any changes to its Privacy Policy.
        <p><strong>Change log:</strong></p>
        <ul>
            <li><em>October 15, 2016:</em>  Copied and then modified from <a href="https://github.com/automattic/legalmattic/blob/master/Privacy-Policy.md">https://github.com/automattic/legalmattic/blob/master/Privacy-Policy.md</a></li>
        </ul>
    </div>